Remove form input trailing spaces (Closes #298)
whynotearth/BrowTricks pull request #322
Opened 2020-09-27 21:49 UTC by colinkiama

# Issue Being Addressed

Put the issue(s) # that your PR is addressing here. e.g. `#15`, `#29`

#298 

# Type of PR

Put an `x` in the brackets for the type(s) of PR this is. You may tick more than one.

[X] Bug Fix
[ ] Refactor
[ ] New Feature
[ ] Update to Existing Feature
[ ] Other (state below)

# Description

**For Bug Fixes:** What was the root cause? How do your changes fix the bug effectively?

- Initially, there wasn't anything being done to remove the trailing whitespace from form inputs.
- These commits fix the bug by:
   - Adding a trim filter to the **MaterialInput** component.
  - Updating views that use the MaterialInput so that the modal attribute on them also includes the "trim" modifier.

# How to Test/Reproduce

Provide steps on how one can test your changes here. e.g.
1. Click on 'Create an account'
2. Fill in each form input while including whitespace at the beginning of the value you entered
3. Focus away from an input
4. Focus on the input again. You'll see that all the trailing whitespace has been removed

**Note**: If form validation fails for an input, the whitespace may not be removed right away, however, if you submit the form after fixing the validation errors, the submitted values will have trailing whitespace removed from them.

2020-09-27 21:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/whynotearth/BrowTricks?pullRequest=322) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/whynotearth/BrowTricks?pullRequest=322) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/whynotearth/BrowTricks?pullRequest=322) it.</sub>

2020-09-28 03:04 UTC, paulchrisluke approved these changes
UX is approve, thank you for your contribution! Going to let @mort3za approve code before merging 👍

2020-09-28 03:34 UTC, giteshk11 requested changes

2020-09-28 03:34 UTC, giteshk11 commented on src/components/inputs/MaterialInput.vue
> +      :value="value | trim"
using a computed method would be a good idea here as filters are removed in  vue 3

2020-09-28 08:13 UTC, merged

2020-10-08 21:28 UTC, colinkiama commented on src/components/inputs/MaterialInput.vue
> +      :value="value | trim"
I'm having difficulty trying to implement the same behaviour with a computed method. Maybe trimming the value in the "onInput" method might be a better alternative.