Added AuthSendEmailSuccess.vue #380
whynotearth/BrowTricks pull request #385
Opened 2020-10-06 09:22 UTC by giteshk11

# Issue Being Addressed

#380 

# Type of PR

Put an `x` in the brackets for the type(s) of PR this is. You may tick more than one.

[ ] Bug Fix
[ ] Refactor
[x] New Feature
[ ] Update to Existing Feature
[ ] Other (state below)

# Description

**For New Features:** What feature are we adding? Explain your technical approach to doing this.
Added new screen when ther user requests for forget password

# How to Test/Reproduce

Provide steps on how one can test your changes here. e.g.
1. Click on forget password
2. Enter Email and click on the button
4. The new screen should be visible

# Screenshots/casts

If applicable, include any relevant screenshot or screencasts of your changes.

2020-10-06 11:05 UTC, paulchrisluke commented
this was successful, but when I press the link in the email I get 
https://deploy-preview-385--browtricks.netlify.app/reset?email=chris%40whynot.earth&token=CfDJ8Lmp%2FloC2NtHgpfrZlrtgOtvnbOb0URl7xp%2F0m3oJB3KUrD8NjuGloxqXdinTctKN4veCD%2Fs0gTasgmSQFWMKghF7e6hIu8wh1zHOws3oDlnWz%2Fzf9HGEFpfd8Ty1Ss1aAIho1SfdyFrlC4ubdAOKQbMCsE%2FLAzOQQkvY9pheI%2Bua%2FnmBuL3LjBV3u3BXLmVvg%3D%3D
![image](https://user-images.githubusercontent.com/5694308/95193751-820e6080-07fe-11eb-938d-06059b312874.png)

2020-10-06 12:29 UTC, mort3za commented
@giteshk11 

change `if (!this.userName || !this.token) {` to check also email in url. (for fixing the issue that chris mentioned)

2020-10-07 04:59 UTC, paulchrisluke approved these changes
lets merge this and test with more recent staging changes

2020-10-07 06:20 UTC, mort3za requested changes

2020-10-07 06:20 UTC, mort3za commented on src/views/AuthForgotPassword.vue
> +            :serverErrors="serverErrors.email"
`serverErrors.Email` is correct

2020-10-07 06:20 UTC, mort3za commented on src/views/AuthResetPassword.vue
> +    if (!this.userName || !this.token || !this.email) {
it should be `!(this.userName || this.email) || !this.token`.

2020-10-07 06:20 UTC, mort3za commented on src/views/AuthResetPassword.vue
> +      return this.$route.email;
I don't see any usage of this computed variable. anyway it should be `return this.$route.query.email` is correct, we want to read the email query parameter in url.

2020-10-07 06:22 UTC, mort3za commented
Please merge staging to your branch and test it again. I encountered this error: 

Sorry, This page is not valid. Please check the link and try again.

2020-10-07 07:18 UTC, mort3za approved these changes

2020-10-07 07:19 UTC, merged