Added splash screen. #415
whynotearth/BrowTricks pull request #427
Opened 2020-10-09 17:20 UTC by giteshk11

# Issue Being Addressed

#415 

# Type of PR

Put an `x` in the brackets for the type(s) of PR this is. You may tick more than one.

[ ] Bug Fix
[ ] Refactor
[x] New Feature
[ ] Update to Existing Feature
[ ] Other (state below)

# Description
Added Splash screen

# Screenshots/casts
https://cdn.discordapp.com/attachments/732444678351355984/764171859989233674/j0pgwlXLq5.mp4

# Additional Context

Provide any additional notes that you think would help effective review of your code.

2020-10-09 17:24 UTC, paulchrisluke approved these changes
so pretty <3

2020-10-13 07:40 UTC, mort3za commented
@paulchrisluke The splash will be shown only in homepage, is it intended?

2020-10-13 07:41 UTC, paulchrisluke commented
anytime someone opens the app please @mort3za

2020-10-13 07:44 UTC, mort3za requested changes

2020-10-13 07:44 UTC, mort3za commented on src/views/Home.vue
> +      <Splash />
Usage of splash component should be in App.vue

2020-10-13 07:44 UTC, mort3za commented on src/views/Home.vue
> +  <div class="w-full h-screen">
We don't use h-screen anywhere. Instead, use h-vh100 please.

2020-10-22 10:09 UTC, paulchrisluke commented
@mort3za @giteshk11 is currently on foodouken could you finish this one up when you have time?

2020-10-22 15:24 UTC, mort3za commented
Sure.

2020-10-23 08:05 UTC, closed without merging